return {
	ansi = {
		"#45475a",
		"#f38ba8",
		"#a6e3a1",
		"#f9e2af",
		"#89b4fa",
		"#f5c2e7",
		"#94e2d5",
		"#bac2de",
	},
	background = "#352939",
	brights = {
		"#585b70",
		"#f38ba8",
		"#a6e3a1",
		"#f9e2af",
		"#89b4fa",
		"#f5c2e7",
		"#94e2d5",
		"#a6adc8",
	},
	compose_cursor = "#DEBAD4",
	cursor_bg = "#F4CDE9",
	cursor_border = "#F4CDE9",
	cursor_fg = "#1a1016",
	foreground = "#F4CDE9",
	indexed = {
		[16] = "#fab387",
		[17] = "#f5e0dc",
	},
	scrollbar_thumb = "#C8A6BE",
	selection_bg = "#F4CDE9",
	selection_fg = "#F4CDE9",
	split = "#DEBAD4",
	tab_bar = {
		active_tab = {
			bg_color = "#F4CDE9",
			fg_color = "#1a1016",
			intensity = "Normal",
			italic = false,
			strikethrough = false,
			underline = "None",
		},
		background = "#1a1016",
		inactive_tab = {
			bg_color = "#5A4551",
			fg_color = "#B293A8",
			intensity = "Normal",
			italic = false,
			strikethrough = false,
			underline = "None",
		},
		inactive_tab_edge = "#5A4551",
		inactive_tab_hover = {
			bg_color = "#705867",
			fg_color = "#C8A6BE",
			intensity = "Normal",
			italic = false,
			strikethrough = false,
			underline = "None",
		},
		new_tab = {
			bg_color = "#866C7D",
			fg_color = "#DEBAD4",
			intensity = "Normal",
			italic = false,
			strikethrough = false,
			underline = "None",
		},
		new_tab_hover = {
			bg_color = "#9C7F92",
			fg_color = "#F4CDE9",
			intensity = "Normal",
			italic = false,
			strikethrough = false,
			underline = "None",
		},
	},
	visual_bell = "#313244",
}
